// Export ApiError from auth only to avoid conflicts
export type {
  Admin,
  ApiError,
  AuthError,
  AuthResponse,
  AuthState,
  ForgotPasswordRequest,
  ForgotPasswordResponse,
  LoginRequest,
  MessageResponse,
  RegisterRequest,
  ResendVerificationRequest,
  ResetPasswordRequest,
  ResetPasswordResponse,
  VerifyEmailRequest,
  VerifyResetCodeRequest,
  VerifyResetCodeResponse,
} from "./auth";
export type {
  Client,
  ClientError,
  ClientResponse,
  ClientsResponse,
  CreateClientFormData,
  DeleteClientResponse,
  Measurement,
  StyleImage,
  UpdateClientFormData,
} from "./client";
